export const pricingPlans = [
  {
    name: "Free",
    slug: "free",
    price: 0,
    tagline: "Try PrimeWebKit with no commitment",
    features: ["1 chatbot", "100 messages / month", "1 knowledge source", "Community support"],
    cta: "Start for free",
    highlighted: false,
  },
  {
    name: "Starter",
    slug: "starter",
    price: 29,
    tagline: "For small teams launching their first bot",
    features: ["3 chatbots", "2,000 messages / month", "Unlimited knowledge sources", "Lead capture & webhooks", "Email support"],
    cta: "Start free trial",
    highlighted: true,
  },
  {
    name: "Pro",
    slug: "pro",
    price: 59,
    tagline: "For growing teams that need the full toolkit",
    features: [
      "10 chatbots",
      "10,000 messages / month",
      "API access & analytics",
      "White-label branding",
      "Custom domain",
      "Priority support",
    ],
    cta: "Start free trial",
    highlighted: false,
  },
  {
    name: "Enterprise",
    slug: "enterprise",
    price: 199,
    tagline: "For large teams with high-volume support",
    features: [
      "Unlimited chatbots",
      "Unlimited messages",
      "API access & analytics",
      "White-label branding",
      "Custom domain",
      "Priority support",
    ],
    cta: "Get Enterprise",
    highlighted: false,
  },
] as const;
